app = "vistormu"
primary_region = "mad"

[build.args]
GO_VERSION = "1.22"

[env]
PORT = "8080"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8_080
min_machines_running = 0
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
